import "@/styles/main.css"
import localFont from "next/font/local"
import Header from "@/components/layouts/Header"
import Footer from "@/components/layouts/Footer"

const acorn = localFont({ src: "../fonts/acorn.woff", variable: "--font-acorn" })
const gt = localFont({ src: "../fonts/gt.woff", variable: "--font-gt" })

export const metadata = {
  title: "Fikri Prijanto",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth scroll-pt-8 lg:scroll-pt-0">
      <body className={`bg-blue-600 ${acorn.variable} ${gt.variable}`}>
        <Header />
        <main className="overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
